[build]
   command = "npm install --legacy-peer-deps && npm run build"
   publish = "build"
   ignore = "/bin/false"

[build.environment]
   NODE_VERSION = "20"
   NPM_FLAGS = "--legacy-peer-deps"
   NODE_OPTIONS = "--max_old_space_size=4096"

# Headers for better SEO and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for HTML pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirect rules for SPA
[[redirects]]
  from = "/api/*"
  to = "https://transyncbackend-production.up.railway.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[context.production.environment]
  REACT_APP_API_URL = "https://transyncbackend-production.up.railway.app"
  REACT_APP_WS_URL = "wss://transyncbackend-production.up.railway.app"
  REACT_APP_NAME = "TransSync"
  REACT_APP_VERSION = "1.1.0"
  REACT_APP_DEBUG_MODE = "false"
  REACT_APP_DEFAULT_COUNTRY = "co"
